[package]
name = "lightning-sentinel"
version = "0.1.0"
edition = "2021"
authors = ["tee8z <tee8z@protonmail.com>"]
license = "LICENSE"

description = "A tool to be notified if lightning node went done via REST requests over tor & a telegram message"

[dependencies]
anyhow = "1.0"
libtor = "46.6.1+0.4.6.6"
log = "0.4.14"
config = "0.11.0"
reqwest = { version = "0.11.7", features = ["socks"] }
tokio = { version = "1.14.0", features = ["full", "time", "sync"] }
futures = "0.3.18"
lazy_static = "1.4"
