[package]
name = "lightning-sentinel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
libtor = "46.6.1+0.4.6.6"
log = "0.4.14"
config = "0.9"
reqwest = { version = "0.11.7", features = ["socks"] }
tokio = { version = "1", features = ["full"] }
