
SOCKS_URL_LOCAL = "socks5h://127.0.0.1"
SOCKS_PORT_LOCAL = 9056
CHECK_URL = "https://<wkdirllfgoofflfXXXXXXXXXXXXXXXXXXXXXXXXXXXXJJJJJJJJJJJJ.onion>:8080"
MACAROON = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"
TELEGRAM_BOT_ID = "9393939339:DKDKDKDKDKDKDKDKDKDKDKDKDKDKDKDKDKD"
TELEGRAM_BASE_URL = "https://api.telegram.org/bot"